version: "3.9"

services:
  ecobot:
    build: .
    image: ecobot:latest
    container_name: ecobot_socket
    env_file:
      - .env
    command: ["python", "-m", "app.server_socket"]
    ports:
      - "5001:5001"
    volumes:
      # Para que puedas ver los gr√°ficos generados por plots.py
      - ./out:/app/out
